# Generated by Django 3.1 on 2020-08-07 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flower',
            name='description_ar',
            field=models.TextField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flower',
            name='title_ar',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
